" Color Scheme
colors industry

" Set compatibility to Vim only
set nocompatible

" Automatically wrap text that extends beyond screen length
set wrap

" Encoding
set encoding=utf-8

" Show line numbers
set number

" Status bar
set laststatus=2
